FROM debian:buster

RUN apt-get update -qq
RUN apt-get upgrade -y
RUN apt-get -y install automake autoconf make gcc wget git build-essential libtool

ADD oqssa /opt/oqssa
RUN echo 'export PATH=/opt/oqssa/bin:$PATH' >> /root/.bashrc

# Default command to run
WORKDIR /home/oqssa/bin
CMD ["/bin/bash"]

