FROM centos:7

RUN yum -y update 

RUN yum -y remove gcc 
RUN yum -y install centos-release-scl 
RUN yum -y install devtoolset-8-gcc* 
RUN yum -y install libtool

ADD oqssa /opt/oqssa
RUN echo 'export PATH=/opt/oqssa/bin:$PATH' >> /root/.bashrc

# Default command to run
WORKDIR /opt/oqssa/bin
ENTRYPOINT source /opt/rh/devtoolset-8/enable && exec "$@"
CMD ["/bin/bash"]

