#!/usr/bin/env bash
#
# Regenerates USAGE-TRACKER.md: a snapshot of how the OQS CI container images
# are used across the open-quantum-safe org.
#
# For every ci-* image on the openquantumsafe Docker Hub namespace it records
# when the image was last published and how many times "openquantumsafe/ci-*"
# is referenced on the default branch of an org repo (the ci-containers repo,
# which produces the images, is excluded). Counts are compared with the previous
# snapshot embedded in the existing file to render an up/down/same trend.
#
# Needs: gh (authenticated via GH_TOKEN), jq, curl, tar. Reads public data only.
# Usage: tools/usage-tracker.sh [output-file]   (default: USAGE-TRACKER.md)
# shellcheck disable=SC2016  # backticks below are literal Markdown code-spans
set -euo pipefail

ORG=open-quantum-safe
NS=openquantumsafe

# build_cur emits the current snapshot as compact JSON:
#   {generated, images:{<name>:{last_updated, refs}}}
build_cur() {
  local generated images repos counts
  generated=$(date -u +%Y-%m-%dT%H:%M:%SZ)

  # ci-* images + last-published date. ponytail: one page; the namespace has
  # <100 repos. Add ?page follow on .next if it ever grows past 100.
  images=$(curl -fsSL "https://hub.docker.com/v2/repositories/${NS}/?page_size=100" \
    | jq '[.results[] | select(.name | startswith("ci-")) | {name, last_updated}]')

  # every public org repo and its default branch
  repos=$(gh api --paginate "orgs/${ORG}/repos?type=public&per_page=100" \
    --jq '.[] | "\(.name) \(.default_branch)"')

  # count references by streaming each repo's default-branch tarball through grep
  counts=$(
    while read -r name branch; do
      [ -z "$name" ] && continue
      [ "$name" = ci-containers ] && continue
      gh api "repos/${ORG}/${name}/tarball/${branch}" 2>/dev/null \
        | tar -xzO 2>/dev/null \
        | grep -oaE "${NS}/ci-[a-z0-9._-]+" || true
    done <<<"$repos" \
      | sed "s#${NS}/##" | sort | uniq -c | awk '{print $2, $1}' \
      | jq -R -s 'split("\n") | map(select(length > 0) | split(" ")
                  | {key: .[0], value: (.[1] | tonumber)}) | from_entries'
  )

  # zero total matches means auth/network broke, not that nobody uses the images
  if [ "$(jq 'length' <<<"$counts")" -eq 0 ]; then
    echo "error: no image references found across the org; aborting" >&2
    return 1
  fi

  jq -cn --arg gen "$generated" --argjson imgs "$images" --argjson cnts "$counts" \
    '{generated: $gen,
      images: ($imgs | map({key: .name,
                            value: {last_updated: .last_updated, refs: ($cnts[.name] // 0)}})
              | from_entries)}'
}

# render_doc turns a current snapshot ($1) and previous snapshot ($2, may be
# empty) into the full Markdown document. Pure: no network, so it is unit-testable.
render_doc() {
  local cur="$1" prev="${2:-}"
  printf '# OQS CI container usage\n\n'
  printf '_Auto-generated by [`tools/usage-tracker.sh`](tools/usage-tracker.sh) on %s._\n\n' \
    "$(jq -r '.generated[:10]' <<<"$cur")"
  cat <<'EOF'
**Org refs** is the number of times each image is referenced on the default branch of a repository in the [`open-quantum-safe`](https://github.com/open-quantum-safe) organization (workflow files, scripts, docs). The `ci-containers` repository itself is excluded, as it produces rather than consumes these images. **Trend** compares the count with the previous monthly snapshot.

| Image | Last published | Org refs (default branches) | Trend |
|---|---|---:|---|
EOF
  jq -rn --argjson cur "$cur" --argjson prev "${prev:-null}" '
    $cur.images | to_entries | sort_by(-.value.refs, .key)[] |
    ($prev.images[.key].refs) as $p |
    (if $prev == null or $p == null then "🆕 new"
     elif .value.refs > $p then "⬆️ +\(.value.refs - $p)"
     elif .value.refs < $p then "⬇️ \(.value.refs - $p)"
     else "➡️ 0" end) as $t |
    "| `\(.key)` | \(.value.last_updated[:10]) | \(.value.refs) | \($t) |"'
  if [ -z "$prev" ]; then
    printf '\n_This is the initial baseline snapshot; trends appear from next month._\n'
  else
    printf '\n_Previous snapshot: %s._\n' "$(jq -r '.generated[:10]' <<<"$prev")"
  fi
  printf '\n<!-- usage-tracker:data\n%s\n-->\n' "$cur"
}

# selftest exercises the trend branches through the real render path, no network.
# Output is captured first, then matched via here-string: piping into `grep -q`
# would SIGPIPE render_doc and trip pipefail on an otherwise-passing case.
selftest() {
  local cur prev out
  cur='{"generated":"2026-07-23T00:00:00Z","images":{"a":{"last_updated":"2026-01-01T00:00:00Z","refs":8},"b":{"last_updated":"2026-01-01T00:00:00Z","refs":2}}}'
  prev='{"generated":"2026-06-01T00:00:00Z","images":{"a":{"refs":5},"b":{"refs":2}}}'
  out=$(render_doc "$cur" "$prev")
  grep -q '`a`.*⬆️ +3' <<<"$out" || { echo "FAIL: up";   exit 1; }
  grep -q '`b`.*➡️ 0'  <<<"$out" || { echo "FAIL: same"; exit 1; }
  grep -q '`a`.*🆕 new' <<<"$(render_doc "$cur" "")" || { echo "FAIL: new"; exit 1; }
  out=$(render_doc "$cur" '{"generated":"x","images":{"a":{"refs":10}}}')
  grep -q '`a`.*⬇️ -2' <<<"$out" || { echo "FAIL: down"; exit 1; }
  echo "selftest OK"
}

main() {
  local out="${1:-USAGE-TRACKER.md}" prev="" cur
  [ -f "$out" ] && prev=$(sed -n '/<!-- usage-tracker:data/,/-->/p' "$out" | sed '1d;$d')
  cur=$(build_cur)
  render_doc "$cur" "$prev" >"$out"
  echo "wrote $out ($(jq '.images | length' <<<"$cur") images)" >&2
}

case "${1:-}" in
  --selftest) selftest ;;
  *) main "$@" ;;
esac
